complete getCommentsByArticleId and implemented all the necessary tes…
brunoFernandes21/northcoders-news pull request #5
Opened 2023-06-27 14:46 UTC by brunoFernandes21

…ts, including 404 and 400

2023-06-27 15:25 UTC, mezzDavies requested changes
Good stuff Bruno! Just one further test you need to think about though - see my comment below. Please resubmit when you have tested and implemented the required code 🙂

2023-06-27 15:25 UTC, mezzDavies commented on __tests__/app.test.js
> +      expect(comments).toBeSortedBy("created_at", {descending: true})
Good stuff on remembering and implementing this 👍

2023-06-27 15:25 UTC, mezzDavies commented on __tests__/app.test.js
> +    .get("/api/articles/strawberries/comments")
🍓🍓🍓🍓🍓🍓🍓🍓

2023-06-27 15:25 UTC, mezzDavies commented on __tests__/app.test.js
> +  })
There is one other happy path test - what if the article exists but it has no comments? We should return the empty array as these are the comments for that article. You will need to find a way to stop the 404 error being sent in this circumstance.

2023-06-28 07:39 UTC, NRMSMITH approved these changes
Well done! 💘

2023-06-28 07:39 UTC, NRMSMITH commented on __tests__/app.test.js
> +    })
Excellent implementation of feedback Bruno! 💘

2023-06-28 07:40 UTC, merged